### ISSUE TITLE
Could we exit != 0 on push error?

### ISSUE THREAD

**Issue by alexJunger** [dfherr/geminabox-release#10]
Thanks for this useful gem!

Are there specific reasons why an upload error in `inabox_push` does not exit the task with a non-successful status?  Because at the moment, it just prints an error with `Bundler.ui.error`. This sort of prevents embedding it into a larger task flow and react accordingly when the push fails.

https://github.com/dfherr/geminabox-release/blob/master/lib/geminabox-release.rb#L165

**Comment by alexJunger** [comment]
The underlying issue is probably that the server doesn't respond with the correct status code, e.g. on 409

**Comment by dfherr** [comment]
No reason, sounds like a bug. I'll look into it

**Comment by dfherr** [comment]
this should be fixed in version 1.2.0

sorry i totally forgot about this
