### ISSUE TITLE
Do not include `rake release` at all

### ISSUE THREAD

**Issue by kikito** [dfherr/geminabox-release#3]
Hi there,

My Rakefile looks like this:

    # This is literally all I have
    require 'geminabox-release'
    GeminaboxRelease.patch(:use_config => true)

When I list all the available rake actions, I get the geminabox ones, as well as the rubygems one:

    rake build
    rake inabox:forcepush
    rake inabox:push
    rake inabox:release
    rake release # This one releases to Rubygems

Is there a way to *not* create that one? It's easy to forget including `inabox:` before that if you are in a hurry.

**Comment by kikito** [comment]
Update -  I found a way doing this:

    require 'geminabox-release'
    GeminaboxRelease.patch(:use_config => true)

    Rake::Task['release'].clear

I think you should do this by default in your gem. If not possible, please add it as an option. Otherwise please consider at adding a note on the README.

**Comment by dfherr** [comment]
i'll consider adding a option to remove the default bundler tasks

**Comment by dfherr** [comment]
added an option `:remove_release` which actually removes the rake release task, not just disables the actions.
